PTS.MVC/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PTS.Data.Models;

namespace PTS.MVC.Controllers
{
    public class PeopleController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7285/api/");
        HttpClient client;
        public PeopleController()
        {
            client = new HttpClient();
            client.BaseAddress = baseAddress;
        }

        // GET: People
        public async Task<IActionResult> Index()
        {
            IEnumerable<Person> people = null;
            HttpResponseMessage result = client.GetAsync(client.BaseAddress + "PeopleApi/getlist").Result;
            if (result.IsSuccessStatusCode)
            {
                string data = result.Content.ReadAsStringAsync().Result;
                people = JsonConvert.DeserializeObject<IList<Person>>(data);
            }
            else
            {
                people = Enumerable.Empty<Person>();
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            return View(people);
        }

        // GET: People/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            Person person = null;
            var result = await client.GetAsync(client.BaseAddress + "PeopleApi/details/" + id);
            if (result.IsSuccessStatusCode)
            {
                person = await result.Content.ReadAsAsync<Person>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            List<SelectListItem> isAdmin = new()
            {
                new SelectListItem { Value = "True", Text = "Project Manager" },
                new SelectListItem { Value = "False", Text = "Nhân viên" },
            };
            ViewBag.isAdmin = isAdmin;
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Name,Username,Password,Email,TelephoneNo,IsAdministrator")] Person person)
        {
            
            string data = JsonConvert.SerializeObject(person);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "PeopleApi/create", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Thông tin không hợp lệ!");
            }
            return View(person);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            List<SelectListItem> isAdmin = new()
            {
                new SelectListItem { Value = "True", Text = "Project Manager" },
                new SelectListItem { Value = "False", Text = "Nhân viên" },
            };
            ViewBag.isAdmin = isAdmin;
            if (id == null)
            {
                return NotFound();
            }
            Person person = null;
            var result = await client.GetAsync($"PeopleApi/details/{id}");
            if (result.IsSuccessStatusCode)
            {
                person = await result.Content.ReadAsAsync<Person>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Name,Username,Password,Email,TelephoneNo,IsAdministrator")] Person person)
        {
            var response = await client.PutAsJsonAsync(client.BaseAddress + "PeopleApi/update", person);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                List<SelectListItem> isAdmin = new()
            {
                new SelectListItem { Value = "True", Text = "Project Manager" },
                new SelectListItem { Value = "False", Text = "Nhân viên" },
            };
                ViewBag.isAdmin = isAdmin;
                ModelState.AddModelError(string.Empty, "Thông tin không hợp lệ xin hãy thử lại");
            }
            return View(person);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Person person = null;
            var result = await client.GetAsync($"PeopleApi/details/{id}");
            if (result.IsSuccessStatusCode)
            {
                person = await result.Content.ReadAsAsync<Person>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await client.DeleteAsync($"PeopleApi/delete/{id}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            return RedirectToAction(nameof(Index));
        }

    }
}

PTS.MVC/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PTS.Data.Models;

namespace PTS.MVC.Controllers
{
    public class TasksController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7285/api/");
        HttpClient client;
        public TasksController()
        {
            client = new HttpClient();
            client.BaseAddress = baseAddress;
        }

        // GET: Tasks
        public async Task<IActionResult> Index()
        {
            IEnumerable<Data.Models.Task> tasks = null;
            HttpResponseMessage result = client.GetAsync(client.BaseAddress + "TasksApi/getlist").Result;
            if (result.IsSuccessStatusCode)
            {
                string data = result.Content.ReadAsStringAsync().Result;
                tasks = JsonConvert.DeserializeObject<IList<Data.Models.Task>>(data);
            }
            else
            {
                tasks = Enumerable.Empty<Data.Models.Task>();
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            return View(tasks);
        }

        // GET: Tasks/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            Data.Models.Task task = null;
            var result = await client.GetAsync(client.BaseAddress + "TasksApi/details/" + id);
            if (result.IsSuccessStatusCode)
            {
                task = await result.Content.ReadAsAsync<Data.Models.Task>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (task == null)
            {
                return NotFound();
            }
            return View(task);
        }

        // GET: Tasks/Create
        public IActionResult Create()
        {
            //ViewBag project
            IEnumerable<Project> projects = null;
            HttpResponseMessage presult = client.GetAsync(client.BaseAddress + "ProjectsApi/getlist").Result;
            if (presult.IsSuccessStatusCode)
            {
                string pdata = presult.Content.ReadAsStringAsync().Result;
                projects = JsonConvert.DeserializeObject<IList<Project>>(pdata);
                List<SelectListItem> projectList = new List<SelectListItem>();
                foreach (var pitem in projects)
                {
                    projectList.Add(new SelectListItem { Value = pitem.ProjectId.ToString(), Text = pitem.Name });
                };
                ViewBag.projectList = projectList;
            }
            //ViewBag team
            IEnumerable<Team> teams = null;
            HttpResponseMessage tresult = client.GetAsync(client.BaseAddress + "TeamsApi/getlist").Result;
            if (tresult.IsSuccessStatusCode)
            {
                string tdata = tresult.Content.ReadAsStringAsync().Result;
                teams = JsonConvert.DeserializeObject<IList<Team>>(tdata);
                List<SelectListItem> teamList = new List<SelectListItem>();
                foreach (var tItem in teams)
                {
                    teamList.Add(new SelectListItem { Value = tItem.TeamId.ToString(), Text = tItem.Name });
                };
                ViewBag.teamList = teamList;
            }
            
            return View();
        }

        // POST: Tasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TaskId,Name,ExpectedDateStarted,ExpectedDateCompleted,ProjectId,TeamId,StatusId")] Data.Models.Task task)
        {
            string data = JsonConvert.SerializeObject(task);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "TasksApi/create", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Details","Projects", new {id = task.ProjectId});
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Sai mã người quản trị hoặc mã khách hàng! Xin vui lòng nhập lại!");
            }
            return View(task);
        }

        // GET: Tasks/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            //ViewBag project
            IEnumerable<Project> projects = null;
            HttpResponseMessage presult = client.GetAsync(client.BaseAddress + "ProjectsApi/getlist").Result;
            if (presult.IsSuccessStatusCode)
            {
                string pdata = presult.Content.ReadAsStringAsync().Result;
                projects = JsonConvert.DeserializeObject<IList<Project>>(pdata);
                List<SelectListItem> projectList = new List<SelectListItem>();
                foreach (var pitem in projects)
                {
                    projectList.Add(new SelectListItem { Value = pitem.ProjectId.ToString(), Text = pitem.Name });
                };
                ViewBag.projectList = projectList;
            }
            //ViewBag team
            IEnumerable<Team> teams = null;
            HttpResponseMessage tresult = client.GetAsync(client.BaseAddress + "TeamsApi/getlist").Result;
            if (tresult.IsSuccessStatusCode)
            {
                string tdata = tresult.Content.ReadAsStringAsync().Result;
                teams = JsonConvert.DeserializeObject<IList<Team>>(tdata);
                List<SelectListItem> teamList = new List<SelectListItem>();
                foreach (var tItem in teams)
                {
                    teamList.Add(new SelectListItem { Value = tItem.TeamId.ToString(), Text = tItem.Name });
                };
                ViewBag.teamList = teamList;
            }
            //ViewBag status
            IEnumerable<Status> statuses = null;
            HttpResponseMessage sresult = client.GetAsync(client.BaseAddress + "TasksApi/getstatuslist").Result;
            if (presult.IsSuccessStatusCode)
            {
                string sdata = sresult.Content.ReadAsStringAsync().Result;
                statuses = JsonConvert.DeserializeObject<IList<Status>>(sdata);
                List<SelectListItem> statusList = new List<SelectListItem>();
                foreach (var sItem in statuses)
                {
                    statusList.Add(new SelectListItem { Value = sItem.StatusId.ToString(), Text = sItem.Name });
                };
                ViewBag.status = statusList;
            }
            if (id == null)
            {
                return NotFound();
            }
            Data.Models.Task task = null;
            var result = await client.GetAsync($"TasksApi/details/{id}");
            if (result.IsSuccessStatusCode)
            {
                task = await result.Content.ReadAsAsync<Data.Models.Task>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (task == null)
            {
                return NotFound();
            }
            return View(task);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("TaskId,Name,ExpectedDateStarted,ExpectedDateCompleted,ActualDateStarted,ActualDateCompleted,ProjectId,TeamId,StatusId,PercentCompleted")] Data.Models.Task task)
        {
            var response = await client.PutAsJsonAsync(client.BaseAddress + "TasksApi/update", task);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Details","Projects", new {id = task.ProjectId});
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Thông tin không hợp lệ xin hãy thử lại");
                //ViewBag project
                IEnumerable<Project> projects = null;
                HttpResponseMessage presult = client.GetAsync(client.BaseAddress + "ProjectsApi/getlist").Result;
                if (presult.IsSuccessStatusCode)
                {
                    string pdata = presult.Content.ReadAsStringAsync().Result;
                    projects = JsonConvert.DeserializeObject<IList<Project>>(pdata);
                    List<SelectListItem> projectList = new List<SelectListItem>();
                    foreach (var pitem in projects)
                    {
                        projectList.Add(new SelectListItem { Value = pitem.ProjectId.ToString(), Text = pitem.Name });
                    };
                    ViewBag.projectList = projectList;
                }
                //ViewBag team
                IEnumerable<Team> teams = null;
                HttpResponseMessage tresult = client.GetAsync(client.BaseAddress + "TeamsApi/getlist").Result;
                if (tresult.IsSuccessStatusCode)
                {
                    string tdata = tresult.Content.ReadAsStringAsync().Result;
                    teams = JsonConvert.DeserializeObject<IList<Team>>(tdata);
                    List<SelectListItem> teamList = new List<SelectListItem>();
                    foreach (var tItem in teams)
                    {
                        teamList.Add(new SelectListItem { Value = tItem.TeamId.ToString(), Text = tItem.Name });
                    };

PTS.MVC/Views/Tasks/Create.cshtml
@model PTS.Data.Models.Task

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Tạo công việc mới</h1>
<hr />
@using (Html.BeginForm("Create", "Tasks", FormMethod.Post))   
{  
    @Html.AntiForgeryToken()  
      
    <div class="form-horizontal">  
        <hr />  
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })  
  
       <div class="form-group">
                <label class="control-label">Tên công việc</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        <div class="form-group">
                <label class="control-label">Ngày bắt đầu dự kiến</label>
                <input asp-for="ExpectedDateStarted" class="form-control" type="date" />
                <span asp-validation-for="ExpectedDateStarted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Ngày kết thúc dự kiến</label>
                <input asp-for="ExpectedDateCompleted" class="form-control" type="date" />
                <span asp-validation-for="ExpectedDateCompleted" class="text-danger"></span>
            </div>
        <div class="form-group">  
            <label class="control-label cold-md-2">Nhóm thực hiện:</label>  
            <div class="col-md-10">  
                <select asp-for="TeamId" class="form-control" asp-items="@ViewBag.teamList"></select>  
                <span asp-validation-for="TeamId" class="text-danger"></span>  
            </div>  
        </div> 
        <div class="form-group">  
            <label class="control-label cold-md-2">Thuộc dự án</label>  
            <div class="col-md-10">  
                <select asp-for="ProjectId" class="form-control" asp-items="@ViewBag.projectList"></select>  
               <span asp-validation-for="ProjectId" class="text-danger"></span>  
            </div>  
        </div>  
        <br>
        <div class="form-group">  
            <div class="col-md-offset-2 col-md-10">  
                <input type="submit" value="Tạo mới" class="btn btn-primary" width="200px" />  
            </div>  
        </div>  
    </div>  
}  

<br />
<div>
    <a asp-action="Index" asp-controller="Projects">Trờ về danh sách dự án</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PTS.MVC/Views/Tasks/Delete.cshtml
@model PTS.Data.Models.Task

@{
    ViewData["Title"] = "Xóa công việc";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Xóa nhân viên</h1>
<br />
<h3>Bạn có chắc muốn xóa công việc: @Html.DisplayFor(item => item.Name)</h3>
<div>
    <hr />
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TaskId" />
        <input type="submit" value="Xóa" class="btn btn-danger" width="200px"/> |
        <a asp-action="Index">Trở về danh sách</a>
    </form>
</div>

PTS.MVC/Views/Tasks/Details.cshtml
@model PTS.Data.Models.Task

@{
    ViewData["Title"] = "Chi tiết công việc";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2>Chi tiết công việc</h2>
<div class="text-left">
        <a asp-action="Edit" asp-route-id="@Model?.TaskId"><input type="submit" value="Chỉnh sửa" class="btn btn-warning" /></a> 
</div>
    <hr />
<div>
    @using (Html.BeginForm()){
        <h3 class="text-center">Công việc: @Html.DisplayFor(item => item.Name)</h3>
        
        <table class="table mt-4 table table-bordered table-hover ">
        <tr>
            <th>Ngày bắt đầu dự kiến</th>
            <td>@Html.DisplayFor(item => item.ExpectedDateStarted)</td>
        </tr>
        <tr>
            <th>Ngày kết thúc dự kiến</th>
            <td>@Html.DisplayFor(item => item.ExpectedDateCompleted)</td>
        </tr>
        <tr>
            <th> Ngày bắt đầu thực tế</th>
            <td>@Html.DisplayFor(item => item.ActualDateStarted)</td>
        </tr>
        <tr>
            <th>Ngày kết thúc thực tế</th>
            <td>@Html.DisplayFor(item => item.ActualDateCompleted)</td>
        </tr>
        <tr>
            <th>Phần trăm hoàn thành</th>
            <td>
                @Html.DisplayFor(item => item.PercentCompleted)%
            </td>
        </tr>
         <tr>
            <th>Trạng thái</th>
            <td>
                @Html.DisplayFor(item => item.Status.Name)
            </td>
        </tr>
        </table>
    <br />
    <hr/>
        <h3>Nhóm thực hiện: @Html.DisplayFor(item => item.Team.Name)</h3>

        <table class="table mt-4 table table-bordered table-hover ">
        <tr>
            <th>Trưởng nhóm</th>
            <td>@Html.DisplayFor(item => item.Team.TeamLeader.Name)</td>
        </tr>
        <tr>
            <th>Số lượng thành viên</th>
            <td>@Model.Team.Users.Count()</td>
        </tr>
        <tr>
            <th>Thành viên nhóm</th>
            
            <td>
                @foreach (var item in Model.Team.Users) {
                <a href="@Url.Action("Details","People", new { id = item.UserId })">@Html.DisplayFor(modelItem => item.Name)</a><br />
                }
            </td>
        </tr>    
        </table>
     <br />
    <hr/>
    <h3>Các công việc nhỏ:</h3>
    <br />
        <table class="table">
    <thead>
        <tr>
            <th>
                Tên công việc
            </th>
            <th>
                Thực hiện bởi
            </th>
            <th>
                Trạng thái
            </th>
            <th>
                Phần trăm hoàn thành
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Subtasks) {
        <tr>
            <td>
               <a href="@Url.Action("Details","Subtasks", new { id = item.SubtaskId })">@Html.DisplayFor(modelItem => item.Name)</a><br />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TeamMember.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PercentCompleted)%
            </td>
        </tr>
}
    </tbody>
</table>
    }
</div>
<br />

PTS.MVC/Views/Tasks/Edit.cshtml
@model PTS.Data.Models.Task

@{
    ViewData["Title"] = "Chỉnh sửa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Chỉnh sửa công việc: <span asp-validation-for="Name" class="text-danger"></span></h1>
<hr />
<br/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TaskId" />
            <div class="form-group">
                <label class="control-label">Tên dự án</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Ngày bắt đầu dự kiến</label>
                <input asp-for="ExpectedDateStarted" class="form-control" type="date" />
                <span asp-validation-for="ExpectedDateStarted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Ngày kết thúc dự kiến</label>
                <input asp-for="ExpectedDateStarted" class="form-control" type="date" />
                <span asp-validation-for="ExpectedDateCompleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Ngày bắt đầu thực tế</label>
                <input asp-for="ActualDateStarted" class="form-control" type="date" />
                <span asp-validation-for="ActualDateStarted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Ngày kết thúc thực tế</label>
                <input asp-for="ActualDateCompleted" class="form-control" type="date" />
                <span asp-validation-for="ActualDateCompleted" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label class="control-label">Thuộc dự án</label>
                <select asp-for="ProjectId" class="form-control" asp-items="@ViewBag.projectList"></select>
                <span asp-validation-for="ProjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Thực hiện bởi</label>
                <select asp-for="TeamId" class="form-control" asp-items="@ViewBag.teamList"></select>
                <span asp-validation-for="TeamId" class="text-danger"></span>
            </div>
            <div class="form-group">
               <label  class="control-label"> Trạng thái</label>
                <select asp-for="StatusId" class="form-control" asp-items="@ViewBag.status"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Phần trăm hoàn thành</label>
                <input asp-for="PercentCompleted" class="form-control" min="0" max="100"/>
                <span asp-validation-for="PercentCompleted" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Lưu thay đổi" class="btn btn-success" width="200px"/>
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index">Trở về danh sách</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PTS.MVC/Views/Tasks/Index.cshtml
@model IEnumerable<PTS.Data.Models.Task>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpectedDateStarted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpectedDateCompleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ActualDateStarted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ActualDateCompleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PercentCompleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Team)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpectedDateStarted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpectedDateCompleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActualDateStarted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActualDateCompleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PercentCompleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Team.Location)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TaskId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TaskId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TaskId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>