PTS.MVC/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PTS.Data.Models;

namespace PTS.MVC.Controllers
{
    public class PeopleController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7285/api/");
        HttpClient client;
        public PeopleController()
        {
            client = new HttpClient();
            client.BaseAddress = baseAddress;
        }

        // GET: People
        public async Task<IActionResult> Index()
        {
            IEnumerable<Person> people = null;
            HttpResponseMessage result = client.GetAsync(client.BaseAddress + "PeopleApi/getlist").Result;
            if (result.IsSuccessStatusCode)
            {
                string data = result.Content.ReadAsStringAsync().Result;
                people = JsonConvert.DeserializeObject<IList<Person>>(data);
            }
            else
            {
                people = Enumerable.Empty<Person>();
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            return View(people);
        }

        // GET: People/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            Person person = null;
            var result = await client.GetAsync(client.BaseAddress + "PeopleApi/details/" + id);
            if (result.IsSuccessStatusCode)
            {
                person = await result.Content.ReadAsAsync<Person>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            List<SelectListItem> isAdmin = new()
            {
                new SelectListItem { Value = "True", Text = "Project Manager" },
                new SelectListItem { Value = "False", Text = "Nhân viên" },
            };
            ViewBag.isAdmin = isAdmin;
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Name,Username,Password,Email,TelephoneNo,IsAdministrator")] Person person)
        {
            
            string data = JsonConvert.SerializeObject(person);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "PeopleApi/create", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Thông tin không hợp lệ!");
            }
            return View(person);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            List<SelectListItem> isAdmin = new()
            {
                new SelectListItem { Value = "True", Text = "Project Manager" },
                new SelectListItem { Value = "False", Text = "Nhân viên" },
            };
            ViewBag.isAdmin = isAdmin;
            if (id == null)
            {
                return NotFound();
            }
            Person person = null;
            var result = await client.GetAsync($"PeopleApi/details/{id}");
            if (result.IsSuccessStatusCode)
            {
                person = await result.Content.ReadAsAsync<Person>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Name,Username,Password,Email,TelephoneNo,IsAdministrator")] Person person)
        {
            var response = await client.PutAsJsonAsync(client.BaseAddress + "PeopleApi/update", person);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                List<SelectListItem> isAdmin = new()
            {
                new SelectListItem { Value = "True", Text = "Project Manager" },
                new SelectListItem { Value = "False", Text = "Nhân viên" },
            };
                ViewBag.isAdmin = isAdmin;
                ModelState.AddModelError(string.Empty, "Thông tin không hợp lệ xin hãy thử lại");
            }
            return View(person);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Person person = null;
            var result = await client.GetAsync($"PeopleApi/details/{id}");
            if (result.IsSuccessStatusCode)
            {
                person = await result.Content.ReadAsAsync<Person>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await client.DeleteAsync($"PeopleApi/delete/{id}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            return RedirectToAction(nameof(Index));
        }

    }
}

PTS.MVC/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PTS.Data.Models;

namespace PTS.MVC.Controllers
{
    public class TeamsController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7285/api/");
        HttpClient client;
        public TeamsController()
        {
            client = new HttpClient();
            client.BaseAddress = baseAddress;
        }

        // GET: Teams
        public async Task<IActionResult> Index()
        {
            IEnumerable<Team> teams = null;
            HttpResponseMessage result = client.GetAsync(client.BaseAddress + "TeamsApi/getlist").Result;
            if (result.IsSuccessStatusCode)
            {
                string data = result.Content.ReadAsStringAsync().Result;
                teams = JsonConvert.DeserializeObject<IList<Team>>(data);
            }
            else
            {
                teams = Enumerable.Empty<Team>();
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            return View(teams);
        }

        // GET: Teams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            Team team = null;
            var result = await client.GetAsync(client.BaseAddress + "TeamsApi/details/" + id);
            if (result.IsSuccessStatusCode)
            {
                team = await result.Content.ReadAsAsync<Team>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        // GET: Teams/Create
        public IActionResult Create()
        {
            List<SelectListItem> isExternal = new()
            {
                new SelectListItem { Value = "True", Text = "Nhóm Outsource" },
                new SelectListItem { Value = "False", Text = "Nhóm Product" },
            };
            ViewBag.isExternal = isExternal;
            //ViewBag teammember
            IEnumerable<Person> people = null;
            HttpResponseMessage result = client.GetAsync(client.BaseAddress + "PeopleApi/getlist").Result;
            if (result.IsSuccessStatusCode)
            {
                string data = result.Content.ReadAsStringAsync().Result;
                people = JsonConvert.DeserializeObject<IList<Person>>(data);
                List<SelectListItem> peopleList = new List<SelectListItem>();
                foreach (var item in people)
                {
                    peopleList.Add(new SelectListItem { Value = item.UserId.ToString(), Text = item.Name });
                };
                ViewBag.TeamLeaderId = peopleList;
            }
            return View();
        }

        // POST: Teams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeamId,Name,Location,TeamLeaderId,IsExternal")] Team team)
        {
            string data = JsonConvert.SerializeObject(team);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "TeamsApi/create", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Thông tin không hợp lệ!");
            }
            return View(team);
        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            List<SelectListItem> isExternal = new()
            {
                new SelectListItem { Value = "True", Text = "Nhóm Outsource" },
                new SelectListItem { Value = "False", Text = "Nhóm Product" },
            };
            ViewBag.isExternal = isExternal;
            //ViewBag teammember
            IEnumerable<Person> people = null;
            HttpResponseMessage presult = client.GetAsync(client.BaseAddress + "PeopleApi/getlist").Result;
            if (presult.IsSuccessStatusCode)
            {
                string pdata = presult.Content.ReadAsStringAsync().Result;
                people = JsonConvert.DeserializeObject<IList<Person>>(pdata);
                List<SelectListItem> peopleList = new List<SelectListItem>();
                foreach (var pitem in people)
                {
                    peopleList.Add(new SelectListItem { Value = pitem.UserId.ToString(), Text = pitem.Name });
                };
                ViewBag.TeamLeaderId = peopleList;
            }
            if (id == null)
            {
                return NotFound();
            }
            Team team = null;
            var result = await client.GetAsync($"TeamsApi/details/{id}");
            if (result.IsSuccessStatusCode)
            {
                team = await result.Content.ReadAsAsync<Team>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TeamId,Name,Location,TeamLeaderId,IsExternal")] Team team)
        {
            var response = await client.PutAsJsonAsync(client.BaseAddress + "TeamsApi/update", team);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Thông tin không hợp lệ xin hãy thử lại");
                List<SelectListItem> isExternal = new()
                {
                new SelectListItem { Value = "True", Text = "Nhóm Outsource" },
                new SelectListItem { Value = "False", Text = "Nhóm Product" },
                };
                ViewBag.isExternal = isExternal;
                //ViewBag teammember
                IEnumerable<Person> people = null;
                HttpResponseMessage presult = client.GetAsync(client.BaseAddress + "PeopleApi/getlist").Result;
                if (presult.IsSuccessStatusCode)
                {
                    string pdata = presult.Content.ReadAsStringAsync().Result;
                    people = JsonConvert.DeserializeObject<IList<Person>>(pdata);
                    List<SelectListItem> peopleList = new List<SelectListItem>();
                    foreach (var pitem in people)
                    {
                        peopleList.Add(new SelectListItem { Value = pitem.UserId.ToString(), Text = pitem.Name });
                    };
                    ViewBag.TeamLeaderId = peopleList;
                }
            }
            return View(team);
        }

        // GET: Teams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Team team = null;
            var result = await client.GetAsync($"TeamsApi/details/{id}");
            if (result.IsSuccessStatusCode)
            {
                team = await result.Content.ReadAsAsync<Team>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await client.DeleteAsync($"TeamsApi/delete/{id}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            return RedirectToAction(nameof(Index));
        }
    }
}

PTS.MVC/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - PTS.MVC</title>
    <!-- google-fonts -->
    <link href="//fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
        rel="stylesheet">
    <!-- //google-fonts -->
    <!-- Template CSS Style link -->
    <link rel="stylesheet" href="~/css/style-starter.css">
</head>

<body>
    <!--header-->
    <header id="site-header" class="fixed-top">
        <div class="container">
            <nav class="navbar navbar-expand-lg stroke">
                <h1>
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img class="img-fluid" src="~/css/logo.png" alt=" "> PTS
                    </a>
                </h1>
                <!-- if logo is image enable this   
    <a class="navbar-brand" href="#index.html">
        <img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
    </a> -->
                <button class="navbar-toggler  collapsed bg-gradient" type="button" data-toggle="collapse"
                    data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon fa icon-expand fa-bars"></span>
                    <span class="navbar-toggler-icon fa icon-close fa-times"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav ml-lg-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Projects" asp-action="Index">Dự án</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Teams" asp-action="Index">Nhóm</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="People" asp-action="Index">Nhân sự</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Customers" asp-action="Index">Khách hàng</a>
                        </li>
                    </ul>
                </div>
                <!-- toggle switch for light and dark theme -->
                <div class="cont-ser-position">
                    <nav class="navigation">
                        <div class="theme-switch-wrapper">
                            <label class="theme-switch" for="checkbox">
                                <input type="checkbox" id="checkbox">
                                <div class="mode-container">
                                    <i class="gg-sun"></i>
                                    <i class="gg-moon"></i>
                                </div>
                            </label>
                        </div>
                    </nav>
                </div>
                <!-- //toggle switch for light and dark theme -->
            </nav>
        </div>
    </header>
    <!--//header-->
    <div class="clear-fix"></div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- footer -->
    <footer class="w3l-footer-22 position-relative mt-5 pt-5">
        <!-- copyright -->
        <div class="copyright-footer text-center">
            <div class="container">
                <div class="columns">
                    <p>Xây dựng ứng dụng quản lý công việc bằng công nghệ .NET - Huỳnh Công Hưng - DA19TTB
                    </p>
                    <p>Giảng viên hướng dẫn: TS. Nguyễn Bảo Ân
                    </p>
                </div>
            </div>
        </div>
        <!-- //copyright -->
    </footer>
    <!-- //footer -->

    <!-- Js scripts -->
    <!-- move top -->
    <button onclick="topFunction()" id="movetop" title="Go to top">
        <span class="fa fa-level-up" aria-hidden="true"></span>
    </button>
    <script>
        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () {
            scrollFunction()
        };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                document.getElementById("movetop").style.display = "block";
            } else {
                document.getElementById("movetop").style.display = "none";
            }
        }

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }
    </script>
    <!-- //move top -->

    <!-- common jquery plugin -->
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <!-- //common jquery plugin -->

    <!-- theme switch js (light and dark)-->
    <script src="~/js/theme-change.js"></script>
    <script>
        function autoType(elementClass, typingSpeed) {
            var thhis = $(elementClass);
            thhis.css({
                "position": "relative",
                "display": "inline-block"
            });
            thhis.prepend('<div class="cursor" style="right: initial; left:0;"></div>');
            thhis = thhis.find(".text-js");
            var text = thhis.text().trim().split('');
            var amntOfChars = text.length;
            var newString = "";
            thhis.text("|");
            setTimeout(function () {
                thhis.css("opacity", 1);
                thhis.prev().removeAttr("style");
                thhis.text("");
                for (var i = 0; i < amntOfChars; i++) {
                    (function (i, char) {
                        setTimeout(function () {
                            newString += char;
                            thhis.text(newString);
                        }, i * typingSpeed);
                    })(i + 1, text[i]);
                }
            }, 1500);
        }

        $(document).ready(function () {
            // Now to start autoTyping just call the autoType function with the 
            // class of outer div
            // The second paramter is the speed between each letter is typed.   
            autoType(".type-js", 200);
        });
    </script>
    <!-- //theme switch js (light and dark)-->

    <!-- magnific popup -->
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.popup-with-zoom-anim').magnificPopup({
                type: 'inline',

                fixedContentPos: false,
                fixedBgPos: true,

                overflowY: 'auto',

                closeBtnInside: true,
                preloader: false,

                midClick: true,
                removalDelay: 300,
                mainClass: 'my-mfp-zoom-in'
            });

            $('.popup-with-move-anim').magnificPopup({
                type: 'inline',

                fixedContentPos: false,
                fixedBgPos: true,

                overflowY: 'auto',

                closeBtnInside: true,
                preloader: false,

                midClick: true,
                removalDelay: 300,
                mainClass: 'my-mfp-slide-bottom'
            });
        });
    </script>
    <!-- //magnific popup -->

    <!-- MENU-JS -->
    <script>
        $(window).on("scroll", function () {
            var scroll = $(window).scrollTop();

            if (scroll >= 80) {
                $("#site-header").addClass("nav-fixed");
            } else {
                $("#site-header").removeClass("nav-fixed");
            }
        });

        //Main navigation Active Class Add Remove
        $(".navbar-toggler").on("click", function () {
            $("header").toggleClass("active");
        });
        $(document).on("ready", function () {
            if ($(window).width() > 991) {
                $("header").removeClass("active");
            }
            $(window).on("resize", function () {
                if ($(window).width() > 991) {
                    $("header").removeClass("active");
                }
            });
        });
    </script>
    <!-- //MENU-JS -->

    <!-- disable body scroll which navbar is in active -->
    <script>
        $(function () {
            $('.navbar-toggler').click(function () {
                $('body').toggleClass('noscroll');
            })
        });
    </script>
    <!-- //disable body scroll which navbar is in active -->

    <!--bootstrap-->
    <script src="~/js/bootstrap.min.js"></script>
    <!-- //bootstrap-->
    <!-- //Js scripts -->
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>