PTS.MVC/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PTS.Data.Models;

namespace PTS.MVC.Controllers
{
    public class CustomersController : Controller
    {

        Uri baseAddress = new Uri("https://localhost:7285/api/");
        HttpClient client;
        public CustomersController()
        {
            client = new HttpClient();
            client.BaseAddress = baseAddress;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            IEnumerable<Customer> customers = null;
            HttpResponseMessage result = client.GetAsync(client.BaseAddress + "CustomersApi/getlist").Result;
            if (result.IsSuccessStatusCode)
            {
                string data = result.Content.ReadAsStringAsync().Result;
                customers = JsonConvert.DeserializeObject<IList<Customer>>(data);
            }
            else
            {
                customers = Enumerable.Empty<Customer>();
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            return View(customers);
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            Customer customer = null;
            var result = await client.GetAsync(client.BaseAddress + "CustomersApi/details/" + id);
            if (result.IsSuccessStatusCode)
            {
                customer = await result.Content.ReadAsAsync<Customer>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerId,Name,Username,Password,Email,TelephoneNo,Company,Country,Address")] Customer customer)
        {
            string data = JsonConvert.SerializeObject(customer);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "CustomersApi/create", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Thông tin không hợp lệ!");
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Customer customer = null;
            var result = await client.GetAsync($"CustomersApi/details/{id}");
            if (result.IsSuccessStatusCode)
            {
                customer = await result.Content.ReadAsAsync<Customer>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerId,Name,Username,Password,Email,TelephoneNo,Company,Country,Address")] Customer customer)
        {
            var response = await client.PutAsJsonAsync(client.BaseAddress + "CustomersApi/update", customer);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Thông tin không hợp lệ xin hãy thử lại");
            }
            return View(customer);
        }

        //// GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Customer customer = null;
            var result = await client.GetAsync($"CustomersApi/details/{id}");
            if (result.IsSuccessStatusCode)
            {
                customer = await result.Content.ReadAsAsync<Customer>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer); 
        }

        //// POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await client.DeleteAsync($"CustomersApi/delete/{id}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
                ModelState.AddModelError(string.Empty, "Người dùng đã đăng ký dự án không thể xóa");
            return RedirectToAction(nameof(Index));
        }
    }
}

PTS.MVC/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PTS.Data.Models;
using System.Net.Http;
using System.Text;

namespace PTS.MVC.Controllers
{
    public class ProjectsController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7285/api/");
        HttpClient client;
        public ProjectsController()
        {
            client = new HttpClient();
            client.BaseAddress = baseAddress;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            IEnumerable<Project> projects = null;
            HttpResponseMessage result = client.GetAsync(client.BaseAddress + "ProjectsApi/getlist").Result;
            if (result.IsSuccessStatusCode)
            {
                string data = result.Content.ReadAsStringAsync().Result;
                projects = JsonConvert.DeserializeObject<IList<Project>>(data);
            }
            else
            {
                projects = Enumerable.Empty<Project>();
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            return View(projects);
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            Project project = null;
            var result = await client.GetAsync(client.BaseAddress + "ProjectsApi/details/" + id);
            if (result.IsSuccessStatusCode)
            {
                project = await result.Content.ReadAsAsync<Project>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        //// GET: Projects/Create
        public IActionResult Create()
        {
            //ViewBag customer
            IEnumerable<Customer> customers = null;
            HttpResponseMessage cresult = client.GetAsync(client.BaseAddress + "CustomersApi/getlist").Result;
            if (cresult.IsSuccessStatusCode)
            {
                string cdata = cresult.Content.ReadAsStringAsync().Result;
                customers = JsonConvert.DeserializeObject<IList<Customer>>(cdata);
                List<SelectListItem> customerList = new List<SelectListItem>();
                foreach (var citem in customers)
                {
                    customerList.Add(new SelectListItem { Value = citem.CustomerId.ToString(), Text = citem.Name });
                };
                ViewBag.customerList = customerList;
            }
            //ViewBag Admin
            IEnumerable<Person> admin = null;
            HttpResponseMessage aresult = client.GetAsync(client.BaseAddress + "PeopleApi/getadminlist").Result;
            if (aresult.IsSuccessStatusCode)
            {
                string adata = aresult.Content.ReadAsStringAsync().Result;
                admin = JsonConvert.DeserializeObject<IList<Person>>(adata);
                List<SelectListItem> adminList = new List<SelectListItem>();
                foreach (var aitem in admin)
                {
                    adminList.Add(new SelectListItem { Value = aitem.UserId.ToString(), Text = aitem.Name });
                };
                ViewBag.adminList = adminList;
            }

            return View();
        }

        //// POST: Projects/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("ProjectId,Name,ExpectedStartDate,ExpectedEndDate,CustomerId,AdministratorId")] Project project)
        {
            
            string data = JsonConvert.SerializeObject(project);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "ProjectsApi/create", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Sai mã người quản trị hoặc mã khách hàng! Xin vui lòng nhập lại!");
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Project project = null;
            var result = await client.GetAsync($"ProjectsApi/details/{id}");
            if (result.IsSuccessStatusCode)
            {
                project = await result.Content.ReadAsAsync<Project>();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            if (project == null)
            {
                return NotFound();
            }

            List<SelectListItem> completed = new()
            {
                new SelectListItem { Value = "True", Text = "Đã hoàn thành" },
                new SelectListItem { Value = "False", Text = "Chưa hoàn thành" },
            };
            ViewBag.completed = completed;
            //ViewBag customer
            IEnumerable<Customer> customers = null;
            HttpResponseMessage cresult = client.GetAsync(client.BaseAddress + "CustomersApi/getlist").Result;
            if (cresult.IsSuccessStatusCode)
            {
                string cdata = cresult.Content.ReadAsStringAsync().Result;
                customers = JsonConvert.DeserializeObject<IList<Customer>>(cdata);
                List<SelectListItem> customerList = new List<SelectListItem>();
                foreach (var citem in customers)
                {
                    customerList.Add(new SelectListItem { Value = citem.CustomerId.ToString(), Text = citem.Name });
                };
                ViewBag.customerList = customerList;
            }
            //ViewBag Admin
            IEnumerable<Person> admin = null;
            HttpResponseMessage aresult = client.GetAsync(client.BaseAddress + "PeopleApi/getadminlist").Result;
            if (aresult.IsSuccessStatusCode)
            {
                string adata = aresult.Content.ReadAsStringAsync().Result;
                admin = JsonConvert.DeserializeObject<IList<Person>>(adata);
                List<SelectListItem> adminList = new List<SelectListItem>();
                foreach (var aitem in admin)
                {
                    adminList.Add(new SelectListItem { Value = aitem.UserId.ToString(), Text = aitem.Name });
                };
                ViewBag.adminList = adminList;
            }
            

            return View(project);
        }

        //// POST: Projects/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ProjectId,Name,ExpectedStartDate,ExpectedEndDate,ActualStartDate,ActualEndDate,Completed,CustomerId,AdministratorId")] Project project)
        {
            var response = await client.PutAsJsonAsync(client.BaseAddress + "ProjectsApi/update", project);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Details",new { id =  project.ProjectId });
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Thông tin không hợp lệ xin hãy thử lại");
                List<SelectListItem> completed = new()
                {
                new SelectListItem { Value = "True", Text = "Đã hoàn thành" },
                new SelectListItem { Value = "False", Text = "Chưa hoàn thành" },
                };
                ViewBag.completed = completed;
                //ViewBag customer
                IEnumerable<Customer> customers = null;
                HttpResponseMessage cresult = client.GetAsync(client.BaseAddress + "CustomersApi/getlist").Result;
                if (cresult.IsSuccessStatusCode)
                {
                    string cdata = cresult.Content.ReadAsStringAsync().Result;
                    customers = JsonConvert.DeserializeObject<IList<Customer>>(cdata);
                    List<SelectListItem> customerList = new List<SelectListItem>();
                    foreach (var citem in customers)
                    {
                        customerList.Add(new SelectListItem { Value = citem.CustomerId.ToString(), Text = citem.Name });
                    };
                    ViewBag.customerList = customerList;
                }
                //ViewBag Admin
                IEnumerable<Person> admin = null;
                HttpResponseMessage aresult = client.GetAsync(client.BaseAddress + "PeopleApi/getadminlist").Result;
                if (aresult.IsSuccessStatusCode)
                {
                    string adata = aresult.Content.ReadAsStringAsync().Result;
                    admin = JsonConvert.DeserializeObject<IList<Person>>(adata);
                    List<SelectListItem> adminList = new List<SelectListItem>();
                    foreach (var aitem in admin)
                    {
                        adminList.Add(new SelectListItem { Value = aitem.UserId.ToString(), Text = aitem.Name });
                    };
                    ViewBag.adminList = adminList;
                }
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {

PTS.MVC/Views/Customers/Create.cshtml
@model PTS.Data.Models.Customer

@{
    ViewData["Title"] = "Tạo khách hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Tạo khách hàng mới</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Tên khách hàng</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Tài khoản</label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Mật khẩu</label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Email</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Số điện thoại</label>
                <input asp-for="TelephoneNo" class="form-control" />
                <span asp-validation-for="TelephoneNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Công ty</label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Quê quán</label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Địa chỉ</label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">  
            <div class="col-md-offset-2 col-md-10">  
                <input type="submit" value="Tạo mới" class="btn btn-primary" width="200px" />  
            </div>  
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Trở về danh sách</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PTS.MVC/Views/Customers/Delete.cshtml
@model PTS.Data.Models.Customer

@{
    ViewData["Title"] = "Xóa khách hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Xóa khách hàng</h1>
<br />
<h3>Bạn có chắc muốn xóa khách hàng: @Html.DisplayFor(item => item.Name)</h3>
<div>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="CustomerId" />
        <input type="submit" value="Xóa" class="btn btn-danger" width="200px"/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PTS.MVC/Views/Customers/Details.cshtml
@model PTS.Data.Models.Customer

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2>Thông tin khách hàng</h2>
    <hr />
<div>
    @using (Html.BeginForm()){
        <h3>Khách hàng: @Html.DisplayFor(item => item.Name)</h3>

        <table class="table mt-4 table table-bordered table-hover ">
        <tr>
            <th>Tên tài khoản</th>
            <td>@Html.DisplayFor(item => item.Username)</td>
        </tr>
        <tr>
            <th>Mật khẩu</th>
            <td>@Html.DisplayFor(item => item.Password)</td>
        </tr>
        <tr>
            <th>Địa chỉ</th>
            <td>@Html.DisplayFor(item => item.Address)</td>
        </tr>
        <tr>
            <th>Số điện thoại</th>
            <td>@Html.DisplayFor(item => item.TelephoneNo)</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>@Html.DisplayFor(item => item.Email)</td>
        </tr>
        <tr>
            <th>Công ty</th>
            <td>@Html.DisplayFor(item => item.Company)</td>
        </tr>     
        </table>
     <br />
     <hr />
     <br />
     <h3>Các dự án đã đăng ký</h3>
    <br />
        <table class="table">
    <thead>
        <tr>
            <th>
                Tên dự án
            </th>
            <th>
                Ngày bắt đầu dự kiến
            </th>
            <th>
                Ngày kết thúc dự kiến
            </th>
            <th>
                Người quản trị
            </th>
            <th>
                Trạng thái
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Projects) {
        <tr>
            <td>
                <a href="@Url.Action("Details","Projects", new { id = item.CustomerId })">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpectedStartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpectedEndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Administrator.Name)
            </td>
            <td>
                @if (item.Completed)
                    {
                        <p style="color:black!important;">Đã hoàn thành</p>
                    }
                    else
                    {
                        <p style="color:black!important;">Chưa hoàn thành</p>
                    }
            </td>
        </tr>
}
    </tbody>
</table>
    }
</div>
<br />
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CustomerId"><input type="submit" value="Chỉnh sửa" class="btn btn-warning" /></a>  &nbsp&nbsp
    <a asp-action="Index"><input type="submit" value="Trở về" class="btn btn-success" /></a>
</div>

PTS.MVC/Views/Customers/Edit.cshtml
@model PTS.Data.Models.Customer

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Chỉnh sửa thông tin khách hàng: <span asp-validation-for="Name" class="text-danger"></span></h2>
<hr />
<br/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerId" />
            <div class="form-group">
                <label class="control-label">Tên khách hàng</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Tài khoản</label>
                <input asp-for="Username" class="form-control"/>
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Mật khẩu</label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Địa chỉ email</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Số điện thoại</label>
                <input asp-for="TelephoneNo" class="form-control" />
                <span asp-validation-for="TelephoneNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Công ty khách hàng</label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Quê quán</label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Địa chỉ</label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu thay đổi" class="btn btn-success" width="200px"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Customers">Trở về danh sách</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PTS.MVC/Views/Customers/Index.cshtml
@model IEnumerable<PTS.Data.Models.Customer>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Danh sách khách hàng</h1>
<br />
<p>
    <a asp-action="Create"> <input type="button" value="Thêm khách hàng" class="btn btn-primary" width="200px" /></a> 
</p>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<table class="table">
    <thead>
        <tr>
            <th>
                Tên khách hàng
            </th>
            <th>
                Email
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Công ty
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a href="@Url.Action("Details", new { id = item.CustomerId })">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelephoneNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Company)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CustomerId"> <input type="submit" value="Chỉnh sửa" class="btn btn-warning" /></a> 
                &nbsp&nbsp
                <a asp-action="Delete" asp-route-id="@item.CustomerId"> <input type="submit" value="Xóa" class="btn btn-danger" /></a>
            </td>
        </tr>
}
    </tbody>
</table>